# DataFrame

### DataFrame is a 2-dimensional labeled data structure with columns of potentially different types. You can think of it like a spreadsheet or SQL table, or a dict of Series objects. It is generally the most commonly used pandas object. Like Series, DataFrame accepts many different kinds of input:

### 1. Dict of 1D ndarrays, lists, dicts, or Series

### 2. 2-D numpy.ndarray

### 3. Structured or record ndarray

### 4. A Series

### 5. Another DataFrame

### Along with the data, you can optionally pass index (row labels) and columns (column labels) arguments. If you pass an index and / or columns, you are guaranteeing the index and / or columns of the resulting DataFrame. Thus, a dict of Series plus a specific index will discard all data not matching up to the passed index.

### If axis labels are not passed, they will be constructed from the input data based on common sense rules.

## From dict of Series or dicts
#### The resulting index will be the union of the indexes of the various Series. If there are any nested dicts, these will first be converted to Series. If no columns are passed, the columns will be the ordered list of dict keys.

In [2]:
import pandas as pd
import numpy as np

In [4]:
d = {
    "one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"]),
}

In [5]:
d

{'one': a    1.0
 b    2.0
 c    3.0
 dtype: float64,
 'two': a    1.0
 b    2.0
 c    3.0
 d    4.0
 dtype: float64}

In [6]:
dframe=pd.DataFrame(d)

In [7]:
dframe

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [8]:
dframe.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [10]:
dframe.columns

Index(['one', 'two'], dtype='object')

## From dict of ndarrays / lists
#### All ndarrays must share the same length. If an index is passed, it must also be the same length as the arrays. If no index is passed, the result will be range(n), where n is the array length.

In [11]:
d = {"one": [1.0, 2.0, 3.0, 4.0], "two": [4.0, 3.0, 2.0, 1.0]}

In [20]:
df=pd.DataFrame(d,index=["a","b","c","d"])

In [21]:
df

   one  two
a  1.0  4.0
b  2.0  3.0
c  3.0  2.0
d  4.0  1.0

In [22]:
df=df.index["a","b","c","d"]

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [3]:
data={"Year":[2004,None,2006,2007,2008,None,2010],
		 "percentage":[87,89,67,56,98,90,None],
		 "no of Student":[32,65,32,None,75,54,75]}
df=pd.DataFrame(data)
print(df)
print(df.isnull())
print(df.isnull().sum())
new_df=df.fillna({'Year':'Unknown',
    'percentage':100,'no of Student':100
})
print(new_df)

     Year  percentage  no of Student
0  2004.0        87.0           32.0
1     NaN        89.0           65.0
2  2006.0        67.0           32.0
3  2007.0        56.0            NaN
4  2008.0        98.0           75.0
5     NaN        90.0           54.0
6  2010.0         NaN           75.0
    Year  percentage  no of Student
0  False       False          False
1   True       False          False
2  False       False          False
3  False       False           True
4  False       False          False
5   True       False          False
6  False        True          False
Year             2
percentage       1
no of Student    1
dtype: int64
      Year  percentage  no of Student
0   2004.0        87.0           32.0
1  Unknown        89.0           65.0
2   2006.0        67.0           32.0
3   2007.0        56.0          100.0
4   2008.0        98.0           75.0
5  Unknown        90.0           54.0
6   2010.0       100.0           75.0

In [4]:
new_df

      Year  percentage  no of Student
0   2004.0        87.0           32.0
1  Unknown        89.0           65.0
2   2006.0        67.0           32.0
3   2007.0        56.0          100.0
4   2008.0        98.0           75.0
5  Unknown        90.0           54.0
6   2010.0       100.0           75.0